"""empty message

Revision ID: 5329eee1b352
Revises: 
Create Date: 2020-05-01 21:47:13.038904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5329eee1b352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('lastname', sa.String(length=60), nullable=True),
    sa.Column('coren', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medics_coren'), 'medics', ['coren'], unique=False)
    op.create_index(op.f('ix_medics_lastname'), 'medics', ['lastname'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('lastname', sa.String(length=60), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('cadsus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_cadsus'), 'patients', ['cadsus'], unique=False)
    op.create_index(op.f('ix_patients_lastname'), 'patients', ['lastname'], unique=False)
    op.create_table('secretaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secretaries_email'), 'secretaries', ['email'], unique=True)
    op.create_index(op.f('ix_secretaries_last_name'), 'secretaries', ['last_name'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_secretary', sa.Integer(), nullable=True),
    sa.Column('id_patient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_patient'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['id_secretary'], ['secretaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetimestamp', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(length=60), nullable=True),
    sa.Column('id_record', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_record'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_datetimestamp'), 'appointments', ['datetimestamp'], unique=False)
    op.create_index(op.f('ix_appointments_place'), 'appointments', ['place'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_place'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_datetimestamp'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('records')
    op.drop_index(op.f('ix_secretaries_last_name'), table_name='secretaries')
    op.drop_index(op.f('ix_secretaries_email'), table_name='secretaries')
    op.drop_table('secretaries')
    op.drop_index(op.f('ix_patients_lastname'), table_name='patients')
    op.drop_index(op.f('ix_patients_cadsus'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medics_lastname'), table_name='medics')
    op.drop_index(op.f('ix_medics_coren'), table_name='medics')
    op.drop_table('medics')
    # ### end Alembic commands ###
